FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-18-bullseye as devcontainer
WORKDIR /root/code/
COPY ../.devcontainer/devcontainer.json ./.devcontainer/devcontainer.json
COPY ../.devcontainer/docker-compose.yml ./.devcontainer/docker-compose.yml
COPY ../.devcontainer/Dockerfile.devcontainer ./.devcontainer/Dockerfile.devcontainer