import { PadProps } from 'utils/props';
import { PadId, ResourceTypeName } from 'utils/types';

export const padsPropData: PadProps[] = [
  {
    __typename: ResourceTypeName.PAD,
    centerX: 531.6,
    centerY: 69.05,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_66,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 531.6,
    centerY: 300,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_63,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 531.6,
    centerY: 531.3,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_60,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 453.95,
    centerY: 146,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_55,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 454,
    centerY: 300.02,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_53,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 454,
    centerY: 453.95,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_51,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 377,
    centerY: 223,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_44,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 377,
    centerY: 300.276,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_43,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 377,
    centerY: 377.276,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_42,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 299.4,
    centerY: 69.05,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_36,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 300.05,
    centerY: 145.95,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_35,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 300,
    centerY: 223,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_34,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 300,
    centerY: 377,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_32,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 299.9,
    centerY: 454,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_31,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 300,
    centerY: 531.6,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_30,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 223,
    centerY: 223,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_24,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 223,
    centerY: 300.276,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_23,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 223,
    centerY: 377,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_22,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 146,
    centerY: 146,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_15,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 145.8,
    centerY: 300.5,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_13,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 146,
    centerY: 454,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_11,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 68.05,
    centerY: 69.05,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_06,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 68.18,
    centerY: 300.4,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_03,
    visitingCow: null,
    selected: false,
  },
  {
    __typename: ResourceTypeName.PAD,
    centerX: 68.18,
    centerY: 531.6,
    radius: 24,
    error: false,
    fill: '#ffffff',
    stroke: '#808080',
    strokeOpacity: 0.5,
    padId: PadId.PAD_00,
    visitingCow: null,
    selected: false,
  },
];
